### PR TITLE
Add support for Ubuntu Noble dependencies

### PR DESCRIPTION
**Pull request by pbusko**
## Summary

Update automation to support Ubuntu Noble based stacks

## Use Cases

Noble based stacks support

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by pbusko** [comment]
Seems like current automation does not correctly react to the addition of new stack. It reports that no version/stack combination needs compilation.

**Comment by loewenstein** [comment]
@paketo-buildpacks/python-maintainers Should we set PR labels (and could we @pbusko)? Seems to me that all other checks are waiting on this one before they even start.

**Comment by loewenstein** [comment]
Ah no, they are waiting for explicit approval from @paketo-buildpacks/python-maintainers

**Review by arjun024 — CHANGES_REQUESTED** [review]
Could you add tests in `dependency/test`?

**Comment by arjun024** [comment]
@pbusko Other than the above comment LGTM - but as is convention do we have an RFC approved to introduce Noble support across Paketo? I couldn't find one.
@paketo-buildpacks/steering-committee Do we have consensus to rollout noble-based dependencies?

**Comment by loewenstein** [comment]
> @pbusko Other than the above comment LGTM - but as is convention do we have an RFC approved to introduce Noble support across Paketo? I couldn't find one. @paketo-buildpacks/steering-committee Do we have consensus to rollout noble-based dependencies?

Hi @arjun024, I was about to reply that "yes, sure we have an RFC to adopt every LTS" but I have to say that I can't find anything other than the specific RFCs for Jammy. However, I recall for sure that we discussed back when Jammy was introduced, that we would adopt every LTS (instead of every other as it was for e.g. the CF buildpacks).

We have discussed in [WG Meetings](https://docs.google.com/document/d/1s-c7PrFkteRRMMPrrVrPx85CwMArdJLMZxNQLq8_mO8/edit#heading=h.qvn5dnbey1az) and on [Slack](https://paketobuildpacks.slack.com/archives/C03K61JJ57A/p1700671561161589) and I actually created [repositories for stacks and buildpackless builders](https://github.com/paketo-buildpacks?q=noble&type=all&language=&sort=) already.

**Comment by arjun024** [comment]
@loewenstein SGTM.
@pbusko Please also rebase the branch onto main after you add the tests. The PR is currently not mergeable.

**Review by arjun024 — APPROVED** [review]

**Pull request merged**
