### PR TITLE
Use draft.Planner from packit directly.

### PR DESCRIPTION
**Pull request by robdimsdale**
- The interface provides limited abstraction over the implementation; there are no side effects of invoking the methods on this object and the increased coupling to packit is acceptable.

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by robdimsdale** [comment]
@paketo-buildpacks/python-maintainers I'm not sure if I prefer this structure or not, so let's discuss it in detail before merging. As far as I can tell, this is the only example of directly constructing an object from `packit`, or any third-party behavior, from within detect/build.

Pros:

* I think the resulting tests are simpler.
* Our unit tests are more representative of the actual behavior.

Cons:

* I think that the code is less consistent because now we sometimes leverage interfaces over `packit` structs, and sometimes we instantiate them directly.
  * This requires more critical reasoning about the code - specifically whether any behavior requires an interface or can be invoked directly.
  * Contrast this to previously, where we could rely on the heuristic that we use an interface for all `packit` behavior.

A couple of other notes:
- There are no noticeable performance changes (speed-ups/slow-downs)
- There are no side-effects of running the `Planner` functions so we don't increase the risk of flakiness/unexpected results.
- We are not increasing or decreasing test coverage - of either happy-path or error cases - in the tests.

Finally, I should also point out that another architecture option is to pass in a concrete instance of `draft.Planner` into the `Build` function. I would argue that this option is worse than the proposed signature (i.e. instantiating the `Planner` directly inside of `Build`), because it increases the coupling further for no additional gain - there is no complexity or performance cost to instantiating the `Planner` so I prefer to encapsulate that within the `Build` function itself rather than exposing it via the signature.

**Comment by robdimsdale** [comment]
cc @joshuatcasey as I know you had thoughts on this structure.

**Comment by joshuatcasey** [comment]
I like several aspects:

- Uses less code to achieve the same result
- Prevents human error by not having to duplicate code (e.g. the `BuildpackPlan` entries and the `entryPlanner.Resolve.Returns` had to match)
- Forces the developer to use only the `BuildpackPlan` to specify the scenario inputs. 

As for introducing variance in how we pull in items from `packit`, I'm personally comfortable with that but I also don't have as much experience as the team looking at dozens of buildpacks. I suspect any improvements start out with some examples, then a few buidpacks are updated, with a team understanding that other buildpacks will be updated as need arises.

TBH I feel like that naming in `packit` (e.g. `"draft".Planner`) and how the thing is actually used (e.g. `entryResolver.MergeLayerTypes`) seems to have drifted over time. Perhaps these functions receive `"draft".Planner` for the sole purpose of faking?

**Comment by robdimsdale** [comment]
> TBH I feel like that naming in `packit` (e.g. `"draft".Planner`) and how the thing is actually used (e.g. `entryResolver.MergeLayerTypes`) seems to have drifted over time. Perhaps these functions receive "draft".Planner for the sole purpose of faking?

I don't quite follow this. What I think I'm reading is:

"Perhaps the reason that we use an interface (`EntryResolver`) rather than passing in a concrete type (`draft.Planner`) in the `Build` functions is to facilitate mocking out in the tests"

Is that what you mean?

An alternative reading of this is that you are proposing passing in a `draft.Planner` into the `Build` function, which I think is a strictly worse solution than either the current solution (using a locally-defined interface) or the proposed solution (instantiating a concrete `draft.Planner` within the `Build` function)

**Comment by joshuatcasey** [comment]
I'll try to clarify.

I like this: `instantiating a concrete draft.Planner within the Build function`

What I meant was I felt that the naming (`draft`, `planner`, `resolver`) didn't tell me what the functions were actually doing. I might suggest global functions named `SortEntriesByPriority` instead of `Resolver` and `DetermineLayerTypes` instead of `MergeLayerTypes` (although the name does make more sense now than it did when I joined). It's also not clear to me why these functions receive type `"draft".Planner` except as a way to assist with faking.

**Comment by joshuatcasey** [comment]
@thitch97 when you say logistically, do you mean how to introduce the change in dozens of buildpacks? Or something else?

I personally am fine with a lazy approach- update buildpacks if and when we touch them for some reason. 

I also think there are a handful of checkboxes we end up putting on many buildpacks (SBOM? Latest Buildpack API? Etc) and this can just go live on that list. Probably should enumerate the list though.

**Comment by thitch97** [comment]
>  when you say logistically, do you mean how to introduce the change in dozens of buildpacks? Or something else?

@joshuatcasey Perhaps "logisitically" was the wrong term to use. I'm not as concerned with how to introduce the change as I agree it's something we can file issues for (or not) and do over time. I guess the crux of my concern was this ongoing cognitive overhead @robdimsdale mentioned and extrapolating _that_ across dozens of buildpacks:
> This requires more critical reasoning about the code - specifically whether any behavior requires an interface or can be invoked directly.

I'm beginning to think that's okay though, or at least unavoidable. If there's not much of an impact either way beyond cleaning up tests I'm okay with trying it out.

**Comment by robdimsdale** [comment]
Ok, it sounds like we have a tentative consensus that we like the proposed design over the existing one.

@paketo-buildpacks/python-maintainers can we approve/merge?

**Review by thitch97 — APPROVED** [review]

**Pull request merged**
