### PR TITLE
Add deprecation_date to metadata

### PR DESCRIPTION
**Pull request by c0d1ngm0nk3y**
## Summary

Adding the `deprecation` date to the metadata of the dependencies.

## Use Cases

The user should be aware if the EOL approaches.

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by arjun024** [comment]
Thanks for the PR. Do you have an official source for the dates? Per [RFC 9](https://github.com/paketo-buildpacks/rfcs/blob/main/text/0009-dep-server.md), if the dates are not known/published, we leave them empty.

Ideally this metadata should be generated along with dependency retrieval from the source of the information [here](https://github.com/paketo-buildpacks/cpython/blob/v1.12.0/dependency/retrieval/main.go#L70) - see an example from ruby-mri [here](https://github.com/paketo-buildpacks/mri/blob/v0.14.13/dependency/retrieval/components/metadata.go#L47).

**Comment by c0d1ngm0nk3y** [comment]
> Thanks for the PR. Do you have an official source for the dates? Per [RFC 9](https://github.com/paketo-buildpacks/rfcs/blob/main/text/0009-dep-server.md), if the dates are not known/published, we leave them empty.

@modulo11 Could you provide the link? I kind of took your input without cross checking :)

**Comment by c0d1ngm0nk3y** [comment]
> Do you have an official source for the dates? 

https://devguide.python.org/versions/
https://endoflife.date/python

**Comment by c0d1ngm0nk3y** [comment]
@arjun024 Would getting the data from https://endoflife.date/docs/api be acceptable?

**Comment by arjun024** [comment]
I can't find a trail of where endoflife.date sources their date from. If you can find it, that source is acceptable. Otherwise, you can use the devguide to source the dates in the retrieve program. The data seems to be coming from https://github.com/python/devguide/blob/main/include/release-cycle.json

**Comment by pbusko** [comment]
The `endoflife.date` uses the same data source under the hood. You can find the sources in https://raw.githubusercontent.com/endoflife-date/endoflife.date/master/products/python.md

```yaml
auto:
  methods:
  -   git: https://github.com/python/cpython.git
      # The v is mandatory here because each branch EOL is tagged, e.g. https://github.com/python/cpython/releases/tag/3.6
      regex: ^v(?P<major>[1-9]\d*)\.(?P<minor>\d+)\.?(?P<patch>\d+)?$
  -   release_table: https://devguide.python.org/versions/
      selector: "table"
      fields:
        releaseCycle: "Branch"
        releaseDate: "First release"
        eol: "End of life"
```

**Comment by c0d1ngm0nk3y** [comment]
@paketo-buildpacks/python-maintainers Any updates on this? Rebasing is rather tedious...

**Comment by arjun024** [comment]
@c0d1ngm0nk3y Code LGTM. Can you remove the metadata.json, which I believe you checked-in in error?

**Comment by c0d1ngm0nk3y** [comment]
> Code LGTM. Can you remove the metadata.json, which I believe you checked-in in error?

Sorry for the delay. We forgot about that one. I removed the file.

**Review by robdimsdale — APPROVED** [review]
Thanks for setting this up, @c0d1ngm0nk3y

**Pull request merged**
