### PR TITLE
Add `OpenSSL` support into `CPython` compilation (and ensure compilation tests check for SSL linking)

### PR DESCRIPTION
**Pull request by joshuatcasey**
Fix OpenSSL for CPython compilation
- Add openssl to the compilation image
- Run compilation tests on bionic and jammy
- Check for SSL dynamic linking during compilation tests

### CODE REVIEW

**Comment by robdimsdale** [comment]
@joshuatcasey this looks fine, in principle, but i want to explicitly ask if we are comfortable moving away from the `make test` interface, and using github actions instead?

I'm personally fine with that, but it's effectively a breaking change for consumers of the deps workflow so we should be clear about it.

**Comment by joshuatcasey** [comment]
@robdimsdale It's a good point about being a breaking change. Notice that the `test` procedure isn't actually a GitHub Action, even though it's in folder `dependency/actions/test`. When I started off I copied `dependency/actions/compile`, but then it felt like the action just introduced additional complexity without adding anything, so the logic was done directly in the workflow.

The question is really whether we want this change introduced to `github-actions`, in which case we have to answer some questions:
- (A) is this approach generic enough for all buildpacks?
- (B) should we use the same approach for compilation?
- (B) is it worth a breaking change?

Note that using this approach for the `compile` step might not be a breaking change since we're bypassing the action and doing the same logic directly from the workflow. But that feels like getting by on a technicality since buildpack authors would likely want still want to make sure their workflow is compatible and delete any action-specific code.

**Comment by joshuatcasey** [comment]
I'll mark this issue as blocked because really we're discussing https://github.com/paketo-buildpacks/github-config/issues/596.

**Comment by robdimsdale** [comment]
I thought we didn't test the non-compiled dependencies (i.e. the source dependencies for the wildcard stack). Even if I'm wrong, I'm not convinced it's worth trying to test the source dependencies because the buildpack itself is compiling from source so its integration tests would fail if the compilation failed.

**Comment by joshuatcasey** [comment]
> I thought we didn't test the non-compiled dependencies (i.e. the source dependencies for the wildcard stack). Even if I'm wrong, I'm not convinced it's worth trying to test the source dependencies because the buildpack itself is compiling from source so its integration tests would fail if the compilation failed.

Correct. This should only test those dependencies compiled on `jammy` and `bionic`.

**Review by robdimsdale — APPROVED** [review]

**Pull request merged**
